# run_tests.yml

name: Poker Bot CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your code onto the server
    - uses: actions/checkout@v3

    # 2. Set up Python (matching your version)
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3. Install dependencies from your requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Run your test suite
    - name: Run Unit Tests
      run: |
        python -m unittest discover tests

